In [174]:
#Solution 1.Version 1
import numpy as np
M = [[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]]
arr = np.array(M)
arr[:,[0, 1]] = arr[:,[1, 0]]
print(arr)
#Solution 1.Version 2
M = [[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]]
for i in range(len(M)):
    M[i][0],M[i][1]=M[i][1],M[i][0] 
print(M)



[[12 11 13 14]
 [22 21 23 24]
 [32 31 33 34]]


In [187]:
#Solution 2
import numpy as np
M = [[0, 3, 2, 4], [2, 7, 5, 9], [6, 1, 2, 3]]
arr = np.array(M)
result = np.where(arr == np.amax(arr))
coordinates = tuple(zip(result[0], result[1]))

for coord in coordinates:
    print(coord)






(1, 3)


In [ ]:
M = [[0, 3, 2, 4], [2, 7, 5, 9], [6, 1, 2, 3]]
for i in range(len(M)):
    
print(M)

In [150]:
#Solution 3

list_1 = [5, 3, 3, 10, 40]
list_2 = [40, 3, 40, 1, 2]

list_3= list_1+list_2

unique_values=set(list_3)

print(len(unique_values))










6


In [106]:
#Solution 4
students = {"Jane":{"grade":90,"student_number":4012}, 
          "Pat":{"grade":81,"student_number":4052},
          "Denis":{"grade":70,"student_number":4089},
          "Max":{"grade":72,"student_number":4322},
          "Lara":{"grade":74,"student_number":4042}}
sum=0
for student in students.values():
    sum+=float(student["grade"])
    
average=float(sum/len(students))

above=[]
equal=[]
below=[]
for name  in students:
        if student["grade"]>average:
            above.append(name)
            print("Grade(s) of {} are above the average".format(name))
        elif student["grade"]==average:
            equal.append(name)
            print("Grade(s) of {} are equal the average".format(name))
        elif student["grade"]<average:
            below.append(name)
        print("Grade(s) of {} are below the average".format(name))
       

Grade(s) of Jane are above the average
Grade(s) of Pat are above the average
Grade(s) of Denis are above the average
Grade(s) of Max are above the average
Grade(s) of Lara are above the average


In [105]:
students = {"Jane":{"grade":90,"student_number":4012}, 
          "Pat":{"grade":81,"student_number":4052},
          "Denis":{"grade":70,"student_number":4089},
          "Max":{"grade":72,"student_number":4322},
          "Lara":{"grade":74,"student_number":4042}}



In [104]:
#Solution 5

transaction=0
ticket=200

while True:
    number=int(input("How many tickets do you want to buy?\nYou can have minimum 1 and maximum 4 tickets!")) 
    if 1<= number <=4  :
        transaction+=1
   
        ticket= ticket-number
        print(f'{ticket} tickets remainigs')
        print("Transaction: {}".format(transaction))
    elif number>4:
        print("You can have minimum 1 and maximum 4 tickets!")
    elif ticket<4:
        if ticket==3:
            print("You can have minimum 1 and maximum 3 tickets!")
        elif ticket==2:
            print("You can have minimum 1 and maximum 2 tickets!")
        elif ticket==1:
            print("You can have 1 ticket!")     
        print("Transaction: {}".format(transaction))


if ticket==0:
    print("All tickets sold out")
    print("Transaction: {}".format(transaction))

KeyboardInterrupt: Interrupted by user